# Generated by Django 4.2 on 2023-04-30 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 13, 1, 40, 158382, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
