# Generated by Django 4.2.1 on 2023-05-11 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_forum', '0003_alter_response_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 14, 55, 23, 706938, tzinfo=datetime.timezone.utc)),
        ),
    ]
