# Generated by Django 4.2.1 on 2023-05-11 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_forum', '0004_alter_response_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 14, 58, 42, 520736, tzinfo=datetime.timezone.utc)),
        ),
    ]
