# Generated by Django 4.2.1 on 2023-05-11 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_forum', '0005_alter_response_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 15, 2, 57, 384492, tzinfo=datetime.timezone.utc)),
        ),
    ]
