# Generated by Django 4.2.1 on 2023-05-11 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('response_forum', '0007_alter_response_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 15, 21, 2, 850481, tzinfo=datetime.timezone.utc)),
        ),
    ]
